# This manifest was generated by Weave Gitops install.  DO NOT EDIT.
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: webhook-source-provider
  namespace: {{.Namespace}}
spec:
  type: generic
  address: http://wego-app.{{.Namespace}}.svc.cluster.local/gitops/source/event/