name: 'Run Acceptance Tests'
description: 'Invoke ginkgo for a subset of our acceptance tests'
inputs:
  result-prefix:
    description: "prefix for result file name -- eg: 'kustomize-'"
    required: false
    default: ''
  focus-or-skip:
    description: "Which regexps to select and filter -- eg: --focus=KustomizeTest or --skip='KustomizeTest|SmokeTest'"
    required: true
  github-key:
    description: "Key for accessing GitHub"
    required: true
  github-token:
    description: "Token for accessing GitHub"
    required: true
  gitlab-org:
    description: "Gitlab organization"
    required: true
  gitlab-key:
    description: "Key for accessing GitLab"
    required: true
  gitlab-token:
    description: "Token for accessing GitLab"
    required: true
  git-provider:
    description: "Value for running tests either on GitHub or GitLab"
    required: false
  artifacts-base-dir:
    description: "Directory for test artifacts"
    required: true

runs:
  using: "composite"
  steps:
  - name: Install Go
    uses: actions/setup-go@v2
    with:
      go-version: 1.17.x
  - name: Checkout code
    uses: actions/checkout@v2
  - name: Setup selenium standalone server
    if: ${{ github.job == 'ui-tests' }}
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install -y xvfb
      sudo apt-get install -y google-chrome-stable
       # https://chromedriver.storage.googleapis.com/
      CHROMEDRIVER_VERSION=94.0.4606.61
       wget https://chromedriver.storage.googleapis.com/"${CHROMEDRIVER_VERSION}"/chromedriver_linux64.zip
      unzip chromedriver_linux64.zip
      sudo mv -f chromedriver /usr/local/bin/chromedriver
       wget  https://selenium-release.storage.googleapis.com/3.14/selenium-server-standalone-3.14.0.jar
       xvfb-run -a --server-args="-screen 0 1280x1024x24" java -jar ./selenium-server-standalone-3.14.0.jar &
  - name: Setup Kubernetes
    shell: bash
    env:
      KIND_CLUSTER_NAME: ${{ format('katc-{0}', github.run_id) }}
      KIND_CLUSTER_IMAGE: kindest/node:v1.21.1
    run: |
      make local-kind-cluster-with-registry
  - name: Kind-check
    shell: bash
    run: |
      kubectl get pods -A
  - name: Download gitops binaries
    uses: actions/download-artifact@v2
    with:
      name: gitops-binaries
      path: bin
  - name: Change bin permissions
    shell: bash
    run: |
      chmod +x bin/gitops
      ls -la bin
  - name: Download dependencies
    shell: bash
    run: |
      make dependencies
  - name: Set up ssh
    uses: ./.github/actions/setup-ssh
    with:
      github-ssh-private-key: ${{ inputs.github-key }}
      gitlab-ssh-private-key: ${{ inputs.gitlab-key }}
  - name: Configure git settings
    shell: bash
    run: |
      git config --global init.defaultBranch main
      git config --global user.email "weave-test-user@example.com"
      git config --global user.name "Testy McTestFace"
      git config --global url.ssh://git@github.com/.insteadOf https://github.com/
  - name: Run Full Acceptance Suite Except Kustomize Add Tests
    shell: bash
    env:
        GITHUB_ORG: weaveworks-gitops-test
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_KEY: ${{ inputs.github-key }}
        IS_TEST_ENV: "true"
        GITLAB_ORG: ${{ inputs.gitlab-org }}
        GITLAB_PUBLIC_GROUP: public-weave-gitops
        GITLAB_SUBGROUP: weave-gitops-sub
        GITLAB_TOKEN: ${{ inputs.gitlab-token }}
        GITLAB_KEY: ${{ inputs.gitlab-key }}
        ARTIFACTS_BASE_DIR: ${{ inputs.artifacts-base-dir }}
        CHECKPOINT_DISABLE: 1
    run: |
      export PATH=${PATH}:`go env GOPATH`/bin
      export WEGO_BIN_PATH=$(pwd)/bin/gitops
      export CLUSTER_PROVIDER=kubectl
      go get github.com/onsi/ginkgo/ginkgo
      go get github.com/onsi/gomega/...
      if [ "${{ github.job }}" == "smoke-tests-long" ]; then
        export GIT_PROVIDER="${{ inputs.git-provider }}"
      fi
      ACCEPTANCE_TEST_ARGS="${{ inputs.focus-or-skip }} --randomizeSuites --reportFile=${{ env.ARTIFACTS_BASE_DIR }}/${{ inputs.result-prefix }}acceptance-test-results.xml" make acceptance-tests
    if: always()
  - name: Store acceptance test results
    env:
      ARTIFACTS_BASE_DIR: ${{ inputs.artifacts-base-dir }}
    if: ${{ always() }}
    uses: actions/upload-artifact@v2
    with:
      name: ${{ inputs.result-prefix }}acceptance-test-artifacts
      path: ${{ env.ARTIFACTS_BASE_DIR }}
      retention-days: 1
