# This manifest was generated by Weave Gitops install.  DO NOT EDIT.
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: webhook-source-alert
  namespace: {{.Namespace}}
spec:
  providerRef:
    name: webhook-source-provider
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'